name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npm run prisma -- generate"
dev = "npm run prisma -- migrate deploy && npm exec remix vite:dev"
